model:
  base_model: 'VGG16' # CNN to use. Needs to be one of VGG16, VGG19, ResNet, DenseNet
  feature_layer: 'block5_pool'
  trainable_features: False
  temporal: 'LSTM' # one of LSTM or CONV
  LSTM_size: [32] # Size of LSTM Layer, multiple values correspond to stacked LSTM layers. Used if temporal is LSTM
  CONV_filters: [128] # Number of filters in conv temporal layer. Multiple values correspond to stacked conv layers. Used if temporal is CONV
  CONV_filter_sizes: [3] # Size of filters in conv temporal layer. Multiple values correspond to stacked conv layers. Used if temporal is CONV
  window_size: 16 # Size window
  stride: 3 # Stride used in extracting frames from shots
  load_weights: 'model/best.h5'# Load weights of a pretrained network. .h5 file expected. Can be used for finetuning, training continuation or inference
  input_size: [224, 224, 3] # Video shape, (width, height, channels)
  nr_classes: 2
  class_dict:
    pan: 0
    tilt: 1