model:
  base_model: 'VGG16' # CNN to use. Needs to be one of VGG16, VGG19, ResNet, DenseNet
  window_size: 16 # Size window
  stride: 3 # Stride used in extracting frames from shots
  load_weights: 'model/best.h5'# Load weights of a pretrained network. .h5 file expected. Can be used for finetuning, training continuation or inference
  input_size: [224, 224, 3] # Video shape, (width, height, channels)
  nr_classes: 2
  class_dict:
    pan: 0
    tilt: 1

inference:
  csv_file: 'results.csv'

